---
R:
  recommended: 4.3.0
  minimum: 4.2.0
packages:
  tidyverse:
    recommended: 2.0.0
  here: NA
  quarto: NA
rstudio:
  recommended: 2023.03.0
  options:
    save_workspace:
      value: never
      message: >
        Improve reproducibility by never saving the workspace.
        Menu tools > Global options > General
    load_workspace:
      value: FALSE
      message: >
        Set load workspace to FALSE to improve reproducibility.
        Menu tools > Global options > General
    rainbow_parentheses:
      value: TRUE
      message: >
        Rainbow parentheses make it easier to spot missing parentheses.
        Menu tools > Global options > Code > Display
    soft_wrap_r_files:
      value: TRUE
      message: >
        Soft wrap files so you do not need to scroll sideways.
        Menu tools > Global options > Code > Editing
    insert_native_pipe_operator:
      value: TRUE
      message: >
        Use the native pipe operator '|>'.
        Menu tools > Global options > Code > Editing
quarto:
  recommended: 1.3.262
git: NA
---
