---
r_version:
  recommended: 4.2.1
  minimum: 4.1.0
packages:
  tidyverse:
    recommended: 1.3.1
  here: NA
  quarto: NA
rstudio:
  recommended: 2022.07.1
  options:
    save_workspace:
      value: never
    load_workspace:
      value: FALSE
      message: Set load workspace to FALSE to improve reproducibility
quarto:
  recommended: 1.2.198
git: NA
---
